<a href="https://colab.research.google.com/github/ahcamachod/2044-numpy-analisis-numerico-eficiente-con-python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy: Análisis numérico eficiente con Python**

NumPy es una biblioteca de Python que ofrece diversas herramientas y funcionalidades esenciales para la computación científica, incluyendo objetos de matriz multidimensional conocidos como *arrays*, rutinas para operaciones rápidas en matrizes, además de operaciones matemáticas, manipulación de formas, estadística entre otros. Es ampliamente utilizada en áreas como análisis de datos, procesamiento de señales y aprendizaje de máquina.

Para acceder a la documentación de esta biblioteca, puedes hacer clic en el siguiente enlace: https://numpy.org/devdocs/index.html

# Importando las bibliotecas y conectando con Drive

In [2]:
import numpy as np

ano_inicial = 2002
ano_final = 2102
np.arange(ano_inicial, ano_final, 4)

array([2002, 2006, 2010, 2014, 2018, 2022, 2026, 2030, 2034, 2038, 2042,
       2046, 2050, 2054, 2058, 2062, 2066, 2070, 2074, 2078, 2082, 2086,
       2090, 2094, 2098])

In [3]:
import numpy as np

ano_inicial = 2002
ano_final = 2102
np.arange(ano_inicial, ano_final + 1, 4)

array([2002, 2006, 2010, 2014, 2018, 2022, 2026, 2030, 2034, 2038, 2042,
       2046, 2050, 2054, 2058, 2062, 2066, 2070, 2074, 2078, 2082, 2086,
       2090, 2094, 2098, 2102])

In [4]:
import numpy as np

ano_inicial = 2000
ano_final = 2102
np.arange(ano_inicial, ano_final, 4)

array([2000, 2004, 2008, 2012, 2016, 2020, 2024, 2028, 2032, 2036, 2040,
       2044, 2048, 2052, 2056, 2060, 2064, 2068, 2072, 2076, 2080, 2084,
       2088, 2092, 2096, 2100])

In [5]:
import numpy

ano_inicial = 2002
ano_final = 2102
np.arange(ano_inicial, ano_final + 1, 4)

array([2002, 2006, 2010, 2014, 2018, 2022, 2026, 2030, 2034, 2038, 2042,
       2046, 2050, 2054, 2058, 2062, 2066, 2070, 2074, 2078, 2082, 2086,
       2090, 2094, 2098, 2102])

In [7]:
import numpy as np

In [12]:
url = 'https://gist.githubusercontent.com/ahcamachod/41b8a65c5e5b58125401deafb68af460/raw/f84320f69efa1cc3e86e1db054422cfa4869c63e/manzanas.csv'


In [13]:
np.loadtxt(url, delimiter=',')

ValueError: could not convert string '' to float64 at row 0, column 1.

In [14]:
(12*7)+3
# np.arange(1,)

####### Método 1 para cargar nuestro dataset desde Github Gists ########

# url = 'https://gist.githubusercontent.com/ahcamachod/41b8a65c5e5b58125401deafb68af460/raw/f84320f69efa1cc3e86e1db054422cfa4869c63e/manzanas.csv'
# np.loadtxt(url,delimiter=',')


# np.loadtxt(url,delimiter=',',usecols = np.arange(1,88,1))

87

In [15]:
# se toman los 3 año mas tres meses hasta marzo y el parametro de arange debe incluir el ultimo dato
np.arange(1,88,1)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87])

In [16]:
# vamos a corregir el error de las columnas con texto
np.loadtxt(url,delimiter=',',usecols=np.arange(1,88,1))

array([[  1.2013,   2.2013,   3.2013,   4.2013,   5.2013,   6.2013,
          7.2013,   8.2013,   9.2013,  10.2013,  11.2013,  12.2013,
          1.2014,   2.2014,   3.2014,   4.2014,   5.2014,   6.2014,
          7.2014,   8.2014,   9.2014,  10.2014,  11.2014,  12.2014,
          1.2015,   2.2015,   3.2015,   4.2015,   5.2015,   6.2015,
          7.2015,   8.2015,   9.2015,  10.2015,  11.2015,  12.2015,
          1.2016,   2.2016,   3.2016,   4.2016,   5.2016,   6.2016,
          7.2016,   8.2016,   9.2016,  10.2016,  11.2016,  12.2016,
          1.2017,   2.2017,   3.2017,   4.2017,   5.2017,   6.2017,
          7.2017,   8.2017,   9.2017,  10.2017,  11.2017,  12.2017,
          1.2018,   2.2018,   3.2018,   4.2018,   5.2018,   6.2018,
          7.2018,   8.2018,   9.2018,  10.2018,  11.2018,  12.2018,
          1.2019,   2.2019,   3.2019,   4.2019,   5.2019,   6.2019,
          7.2019,   8.2019,   9.2019,  10.2019,  11.2019,  12.2019,
          1.202 ,   2.202 ,   3.202 ],
       [ 

In [18]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [19]:
path = '/content/drive/MyDrive/Colab Notebooks/manzanas.csv'

####### Método 2 para cargar el dataset directamente desde Google Drive #####

In [22]:
np.loadtxt(path,delimiter=',',usecols=np.arange(1,88,1))

array([[  1.2013,   2.2013,   3.2013,   4.2013,   5.2013,   6.2013,
          7.2013,   8.2013,   9.2013,  10.2013,  11.2013,  12.2013,
          1.2014,   2.2014,   3.2014,   4.2014,   5.2014,   6.2014,
          7.2014,   8.2014,   9.2014,  10.2014,  11.2014,  12.2014,
          1.2015,   2.2015,   3.2015,   4.2015,   5.2015,   6.2015,
          7.2015,   8.2015,   9.2015,  10.2015,  11.2015,  12.2015,
          1.2016,   2.2016,   3.2016,   4.2016,   5.2016,   6.2016,
          7.2016,   8.2016,   9.2016,  10.2016,  11.2016,  12.2016,
          1.2017,   2.2017,   3.2017,   4.2017,   5.2017,   6.2017,
          7.2017,   8.2017,   9.2017,  10.2017,  11.2017,  12.2017,
          1.2018,   2.2018,   3.2018,   4.2018,   5.2018,   6.2018,
          7.2018,   8.2018,   9.2018,  10.2018,  11.2018,  12.2018,
          1.2019,   2.2019,   3.2019,   4.2019,   5.2019,   6.2019,
          7.2019,   8.2019,   9.2019,  10.2019,  11.2019,  12.2019,
          1.202 ,   2.202 ,   3.202 ],
       [ 

In [42]:
datos = np.loadtxt(path,delimiter=',',usecols=np.arange(1,88,1))

In [43]:
datos

array([[  1.2013,   2.2013,   3.2013,   4.2013,   5.2013,   6.2013,
          7.2013,   8.2013,   9.2013,  10.2013,  11.2013,  12.2013,
          1.2014,   2.2014,   3.2014,   4.2014,   5.2014,   6.2014,
          7.2014,   8.2014,   9.2014,  10.2014,  11.2014,  12.2014,
          1.2015,   2.2015,   3.2015,   4.2015,   5.2015,   6.2015,
          7.2015,   8.2015,   9.2015,  10.2015,  11.2015,  12.2015,
          1.2016,   2.2016,   3.2016,   4.2016,   5.2016,   6.2016,
          7.2016,   8.2016,   9.2016,  10.2016,  11.2016,  12.2016,
          1.2017,   2.2017,   3.2017,   4.2017,   5.2017,   6.2017,
          7.2017,   8.2017,   9.2017,  10.2017,  11.2017,  12.2017,
          1.2018,   2.2018,   3.2018,   4.2018,   5.2018,   6.2018,
          7.2018,   8.2018,   9.2018,  10.2018,  11.2018,  12.2018,
          1.2019,   2.2019,   3.2019,   4.2019,   5.2019,   6.2019,
          7.2019,   8.2019,   9.2019,  10.2019,  11.2019,  12.2019,
          1.202 ,   2.202 ,   3.202 ],
       [ 

In [26]:
print(datos)

[[  1.2013   2.2013   3.2013   4.2013   5.2013   6.2013   7.2013   8.2013
    9.2013  10.2013  11.2013  12.2013   1.2014   2.2014   3.2014   4.2014
    5.2014   6.2014   7.2014   8.2014   9.2014  10.2014  11.2014  12.2014
    1.2015   2.2015   3.2015   4.2015   5.2015   6.2015   7.2015   8.2015
    9.2015  10.2015  11.2015  12.2015   1.2016   2.2016   3.2016   4.2016
    5.2016   6.2016   7.2016   8.2016   9.2016  10.2016  11.2016  12.2016
    1.2017   2.2017   3.2017   4.2017   5.2017   6.2017   7.2017   8.2017
    9.2017  10.2017  11.2017  12.2017   1.2018   2.2018   3.2018   4.2018
    5.2018   6.2018   7.2018   8.2018   9.2018  10.2018  11.2018  12.2018
    1.2019   2.2019   3.2019   4.2019   5.2019   6.2019   7.2019   8.2019
    9.2019  10.2019  11.2019  12.2019   1.202    2.202    3.202 ]
 [ 79.72    81.08    79.68    79.8     80.63    80.8     80.28    78.99
   76.77    76.09    76.36    77.16    77.5     79.03    80.28    80.05
   78.11    76.9     77.68    76.05    75.53    73

In [27]:
import numpy as np

# crea una lista
lista = [1, 2, 3, 4, 5]

# convierte la lista en un array Numpy
array = np.array(lista)

print("Lista: ", lista)
print("Array: ", array)

Lista:  [1, 2, 3, 4, 5]
Array:  [1 2 3 4 5]


In [28]:
import numpy as np
import time

# crea una lista con 1000000 elementos
lista = list(range(1000000))

# convierte la lista en un array Numpy
array = np.array(lista)

# comienza a medir el tiempo para la operación con la lista
start_time = time.time()

# realiza la operación de elevar al cuadrado cada elemento de la lista
lista_cuadrado = [i**2 for i in lista]

# detiene el cronómetro
tiempo_lista = time.time() - start_time

# comienza a medir el tiempo para la operación con el array
start_time = time.time()

# realiza la operación de elevar al cuadrado cada elemento del array
array_cuadrado = array**2

# detiene el cronómetro
tiempo_array = time.time() - start_time

print("Tiempo de la operación con la lista: ", tiempo_lista)
print("Tiempo de la operación con el array: ", tiempo_array)

Tiempo de la operación con la lista:  0.08920621871948242
Tiempo de la operación con el array:  0.0042836666107177734


#METODOS BASICOS PARA EXPLORAR ARRAYS

In [29]:
datos.ndim

2

In [30]:
datos.shape

(6, 87)

In [31]:
datos

array([[  1.2013,   2.2013,   3.2013,   4.2013,   5.2013,   6.2013,
          7.2013,   8.2013,   9.2013,  10.2013,  11.2013,  12.2013,
          1.2014,   2.2014,   3.2014,   4.2014,   5.2014,   6.2014,
          7.2014,   8.2014,   9.2014,  10.2014,  11.2014,  12.2014,
          1.2015,   2.2015,   3.2015,   4.2015,   5.2015,   6.2015,
          7.2015,   8.2015,   9.2015,  10.2015,  11.2015,  12.2015,
          1.2016,   2.2016,   3.2016,   4.2016,   5.2016,   6.2016,
          7.2016,   8.2016,   9.2016,  10.2016,  11.2016,  12.2016,
          1.2017,   2.2017,   3.2017,   4.2017,   5.2017,   6.2017,
          7.2017,   8.2017,   9.2017,  10.2017,  11.2017,  12.2017,
          1.2018,   2.2018,   3.2018,   4.2018,   5.2018,   6.2018,
          7.2018,   8.2018,   9.2018,  10.2018,  11.2018,  12.2018,
          1.2019,   2.2019,   3.2019,   4.2019,   5.2019,   6.2019,
          7.2019,   8.2019,   9.2019,  10.2019,  11.2019,  12.2019,
          1.202 ,   2.202 ,   3.202 ],
       [ 

In [45]:
datos.T

array([[  1.2013,  79.72  ,  42.67  ,  62.55  ,  48.26  ,  71.25  ],
       [  2.2013,  81.08  ,  44.37  ,  62.73  ,  51.01  ,  71.35  ],
       [  3.2013,  79.68  ,  44.73  ,  63.43  ,  50.91  ,  70.9   ],
       [  4.2013,  79.8   ,  46.75  ,  63.83  ,  53.94  ,  71.92  ],
       [  5.2013,  80.63  ,      nan,  66.06  ,  61.27  ,  72.91  ],
       [  6.2013,  80.8   ,  51.59  ,  69.22  ,  65.44  ,  74.39  ],
       [  7.2013,  80.28  ,  57.8   ,  72.07  ,  56.51  ,  73.1   ],
       [  8.2013,  78.99  ,  62.14  ,  69.31  ,  53.    ,  70.24  ],
       [  9.2013,  76.77  ,  56.76  ,  65.18  ,  43.87  ,  69.12  ],
       [ 10.2013,  76.09  ,  50.85  ,  62.13  ,  42.12  ,  68.98  ],
       [ 11.2013,  76.36  ,  46.43  ,  64.17  ,  43.98  ,  68.58  ],
       [ 12.2013,  77.16  ,  46.73  ,  65.5   ,  44.66  ,  69.5   ],
       [  1.2014,  77.5   ,  45.85  ,  66.85  ,  47.73  ,  70.14  ],
       [  2.2014,  79.03  ,  49.25  ,  68.38  ,  52.31  ,  70.58  ],
       [  3.2014,  80.28  ,  48.14

In [44]:
datos_transpuestos = datos.T
print(datos_transpuestos)

[[  1.2013  79.72    42.67    62.55    48.26    71.25  ]
 [  2.2013  81.08    44.37    62.73    51.01    71.35  ]
 [  3.2013  79.68    44.73    63.43    50.91    70.9   ]
 [  4.2013  79.8     46.75    63.83    53.94    71.92  ]
 [  5.2013  80.63        nan  66.06    61.27    72.91  ]
 [  6.2013  80.8     51.59    69.22    65.44    74.39  ]
 [  7.2013  80.28    57.8     72.07    56.51    73.1   ]
 [  8.2013  78.99    62.14    69.31    53.      70.24  ]
 [  9.2013  76.77    56.76    65.18    43.87    69.12  ]
 [ 10.2013  76.09    50.85    62.13    42.12    68.98  ]
 [ 11.2013  76.36    46.43    64.17    43.98    68.58  ]
 [ 12.2013  77.16    46.73    65.5     44.66    69.5   ]
 [  1.2014  77.5     45.85    66.85    47.73    70.14  ]
 [  2.2014  79.03    49.25    68.38    52.31    70.58  ]
 [  3.2014  80.28    48.14    68.77    56.8     70.78  ]
 [  4.2014  80.05    49.18    69.32    51.15    72.78  ]
 [  5.2014  78.11    49.49    69.77    54.63    72.84  ]
 [  6.2014  76.9     49.83    7

In [36]:
url = 'https://raw.githubusercontent.com/allanspadini/numpy/dados/bytebank.csv'
import numpy as np
dato = np.loadtxt(url, delimiter=',', skiprows=1, dtype=float)
np.shape(dato)

(12, 2)

In [37]:
url = 'https://raw.githubusercontent.com/allanspadini/numpy/dados/bytebank.csv'
import numpy as np
dato = np.loadtxt(url, delimiter=',', skiprows=1, dtype=float)
dato.shape

(12, 2)

In [38]:
url = 'https://raw.githubusercontent.com/allanspadini/numpy/dados/bytebank.csv'
import numpy as np
dato = np.loadtxt(url, delimiter=',', skiprows=1, dtype=float)
dato.ndim

2

In [39]:
url = 'https://raw.githubusercontent.com/allanspadini/numpy/dados/bytebank.csv'
import numpy as np
dato = np.loadtxt(url, delimiter=',', skiprows=[1,2], dtype=float)
np.shape(dato)

TypeError: argument must be an integer

In [47]:
import numpy as np
url = 'https://gist.githubusercontent.com/ahcamachod/9be09de793dc3bf1e6c3d98eb4e5b1ef/raw/21b85572693200040e11284ef6dcfc3457ec8e11/citrus.csv'
datos_a = np.loadtxt(url, delimiter=',', usecols=np.arange(1, 6, 1), skiprows=1)

In [48]:
print(datos_a)

[[  2.96  86.76 172.    85.     2.  ]
 [  3.91  88.05 166.    78.     3.  ]
 [  4.42  95.17 156.    81.     2.  ]
 ...
 [ 15.59 256.5  168.    82.    20.  ]
 [ 15.92 260.14 142.    72.    11.  ]
 [ 16.45 261.51 152.    74.     2.  ]]


In [49]:
datos_a.shape

(10000, 5)

# Visualización y Selección

In [50]:
datos_transpuestos

array([[  1.2013,  79.72  ,  42.67  ,  62.55  ,  48.26  ,  71.25  ],
       [  2.2013,  81.08  ,  44.37  ,  62.73  ,  51.01  ,  71.35  ],
       [  3.2013,  79.68  ,  44.73  ,  63.43  ,  50.91  ,  70.9   ],
       [  4.2013,  79.8   ,  46.75  ,  63.83  ,  53.94  ,  71.92  ],
       [  5.2013,  80.63  ,      nan,  66.06  ,  61.27  ,  72.91  ],
       [  6.2013,  80.8   ,  51.59  ,  69.22  ,  65.44  ,  74.39  ],
       [  7.2013,  80.28  ,  57.8   ,  72.07  ,  56.51  ,  73.1   ],
       [  8.2013,  78.99  ,  62.14  ,  69.31  ,  53.    ,  70.24  ],
       [  9.2013,  76.77  ,  56.76  ,  65.18  ,  43.87  ,  69.12  ],
       [ 10.2013,  76.09  ,  50.85  ,  62.13  ,  42.12  ,  68.98  ],
       [ 11.2013,  76.36  ,  46.43  ,  64.17  ,  43.98  ,  68.58  ],
       [ 12.2013,  77.16  ,  46.73  ,  65.5   ,  44.66  ,  69.5   ],
       [  1.2014,  77.5   ,  45.85  ,  66.85  ,  47.73  ,  70.14  ],
       [  2.2014,  79.03  ,  49.25  ,  68.38  ,  52.31  ,  70.58  ],
       [  3.2014,  80.28  ,  48.14

In [ ]:
fechas = datos_